apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poms-pvc-public
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poms-pvc-logs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi